### ISSUE TITLE
[Bug] Variable not shown

### ISSUE THREAD

**Issue by huajun07** [huajun07/codesketcher#98]
# Bug
- Variable is not shown after the code fully executes
Sample Code:
```python
a = [i for i in range(10)]
```

<img width="1920" alt="image" src="https://github.com/huajun07/codesketcher/assets/35941406/779ae991-9d01-4422-8f4f-5dbaef525ae0">

**Comment by limanjun99** [comment]
## Cause

This issue occurs because of list comprehension. When done on the last line of a function, we will return twice (once from list comprehension, and then immediately again from the function itself). This causes `user_return` in the debugger to be called consecutively without any `user_line` in between. Hence, the `previous_function_scope` we store becomes wrong, and we miss out on adding the variables before the second return.

```
1-st return from list comprehension
-> our debugger thinks this is the correct return, and adds all the variables from here

-> "a" is defined

2-nd return from function
-> our debugger misses out this return (in favour of the 1-st return), causing "a" to be missed out
```

## Temporary Fix

#103 temporarily fixes this, by explicitly checking for returns from `<listcomp>`, and setting a flag. When we reach the 2nd return, because this flag is set, we know to add the variables instead of skipping.
